// Generated by gencpp from file rosky_msgs/CoordinationSignal.msg
// DO NOT EDIT!


#ifndef ROSKY_MSGS_MESSAGE_COORDINATIONSIGNAL_H
#define ROSKY_MSGS_MESSAGE_COORDINATIONSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosky_msgs
{
template <class ContainerAllocator>
struct CoordinationSignal_
{
  typedef CoordinationSignal_<ContainerAllocator> Type;

  CoordinationSignal_()
    : header()
    , signal()  {
    }
  CoordinationSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _signal_type;
  _signal_type signal;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(SIGNAL_A)
  #undef SIGNAL_A
#endif
#if defined(_WIN32) && defined(SIGNAL_B)
  #undef SIGNAL_B
#endif
#if defined(_WIN32) && defined(SIGNAL_C)
  #undef SIGNAL_C
#endif
#if defined(_WIN32) && defined(TL_GO_ALL)
  #undef TL_GO_ALL
#endif
#if defined(_WIN32) && defined(TL_STOP_ALL)
  #undef TL_STOP_ALL
#endif
#if defined(_WIN32) && defined(TL_GO_N)
  #undef TL_GO_N
#endif
#if defined(_WIN32) && defined(TL_GO_S)
  #undef TL_GO_S
#endif
#if defined(_WIN32) && defined(TL_GO_W)
  #undef TL_GO_W
#endif
#if defined(_WIN32) && defined(TL_GO_E)
  #undef TL_GO_E
#endif
#if defined(_WIN32) && defined(TL_YIELD)
  #undef TL_YIELD
#endif


  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  OFF;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  SIGNAL_A;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  SIGNAL_B;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  SIGNAL_C;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_GO_ALL;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_STOP_ALL;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_GO_N;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_GO_S;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_GO_W;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_GO_E;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TL_YIELD;

  typedef boost::shared_ptr< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinationSignal_

typedef ::rosky_msgs::CoordinationSignal_<std::allocator<void> > CoordinationSignal;

typedef boost::shared_ptr< ::rosky_msgs::CoordinationSignal > CoordinationSignalPtr;
typedef boost::shared_ptr< ::rosky_msgs::CoordinationSignal const> CoordinationSignalConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::OFF =
        
          "light_off"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::SIGNAL_A =
        
          "CAR_SIGNAL_A"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::SIGNAL_B =
        
          "CAR_SIGNAL_B"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::SIGNAL_C =
        
          "CAR_SIGNAL_C"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_GO_ALL =
        
          "tl_go_all"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_STOP_ALL =
        
          "tl_stop_all"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_GO_N =
        
          "tl_go_N"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_GO_S =
        
          "tl_go_S"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_GO_W =
        
          "tl_go_W"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_GO_E =
        
          "tl_go_E"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      CoordinationSignal_<ContainerAllocator>::TL_YIELD =
        
          "tl_yield"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosky_msgs::CoordinationSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosky_msgs::CoordinationSignal_<ContainerAllocator1> & lhs, const ::rosky_msgs::CoordinationSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosky_msgs::CoordinationSignal_<ContainerAllocator1> & lhs, const ::rosky_msgs::CoordinationSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosky_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38d01c6c7727f64c628b7afcb3e7ccd2";
  }

  static const char* value(const ::rosky_msgs::CoordinationSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38d01c6c7727f64cULL;
  static const uint64_t static_value2 = 0x628b7afcb3e7ccd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosky_msgs/CoordinationSignal";
  }

  static const char* value(const ::rosky_msgs::CoordinationSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string signal\n"
"\n"
"# these must match with LED_protocol.yaml\n"
"string OFF=light_off\n"
"string SIGNAL_A=CAR_SIGNAL_A\n"
"string SIGNAL_B=CAR_SIGNAL_B\n"
"string SIGNAL_C=CAR_SIGNAL_C\n"
"\n"
"string TL_GO_ALL=tl_go_all\n"
"string TL_STOP_ALL=tl_stop_all\n"
"string TL_GO_N=tl_go_N\n"
"string TL_GO_S=tl_go_S\n"
"string TL_GO_W=tl_go_W\n"
"string TL_GO_E=tl_go_E\n"
"string TL_YIELD=tl_yield\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rosky_msgs::CoordinationSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinationSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosky_msgs::CoordinationSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosky_msgs::CoordinationSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSKY_MSGS_MESSAGE_COORDINATIONSIGNAL_H
