// Generated by gencpp from file rosky_msgs/DuckieSensor.msg
// DO NOT EDIT!


#ifndef ROSKY_MSGS_MESSAGE_DUCKIESENSOR_H
#define ROSKY_MSGS_MESSAGE_DUCKIESENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosky_msgs
{
template <class ContainerAllocator>
struct DuckieSensor_
{
  typedef DuckieSensor_<ContainerAllocator> Type;

  DuckieSensor_()
    : value(0)
    , fvalue(0.0)
    , is_analog(false)
    , name()  {
    }
  DuckieSensor_(const ContainerAllocator& _alloc)
    : value(0)
    , fvalue(0.0)
    , is_analog(false)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _value_type;
  _value_type value;

   typedef float _fvalue_type;
  _fvalue_type fvalue;

   typedef uint8_t _is_analog_type;
  _is_analog_type is_analog;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::rosky_msgs::DuckieSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosky_msgs::DuckieSensor_<ContainerAllocator> const> ConstPtr;

}; // struct DuckieSensor_

typedef ::rosky_msgs::DuckieSensor_<std::allocator<void> > DuckieSensor;

typedef boost::shared_ptr< ::rosky_msgs::DuckieSensor > DuckieSensorPtr;
typedef boost::shared_ptr< ::rosky_msgs::DuckieSensor const> DuckieSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosky_msgs::DuckieSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosky_msgs::DuckieSensor_<ContainerAllocator1> & lhs, const ::rosky_msgs::DuckieSensor_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.fvalue == rhs.fvalue &&
    lhs.is_analog == rhs.is_analog &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosky_msgs::DuckieSensor_<ContainerAllocator1> & lhs, const ::rosky_msgs::DuckieSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosky_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosky_msgs::DuckieSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosky_msgs::DuckieSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosky_msgs::DuckieSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3337f0684bf5f2b309fb6921917219f7";
  }

  static const char* value(const ::rosky_msgs::DuckieSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3337f0684bf5f2b3ULL;
  static const uint64_t static_value2 = 0x09fb6921917219f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosky_msgs/DuckieSensor";
  }

  static const char* value(const ::rosky_msgs::DuckieSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Sensors send value and type messages\n"
"# For analog sensors value = 0..4097 and fvalue = 0.0..1.0\n"
"# For digital sensors value= 0..1 and fvalue = 0.0\n"
"uint16 value\n"
"float32 fvalue\n"
"bool is_analog\n"
"string name\n"
;
  }

  static const char* value(const ::rosky_msgs::DuckieSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.fvalue);
      stream.next(m.is_analog);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DuckieSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosky_msgs::DuckieSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosky_msgs::DuckieSensor_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
    s << indent << "fvalue: ";
    Printer<float>::stream(s, indent + "  ", v.fvalue);
    s << indent << "is_analog: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_analog);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSKY_MSGS_MESSAGE_DUCKIESENSOR_H
