//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the rosky_msgs package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __rosky_msgs__LANE_FILTER_PARAMCONFIG_H__
#define __rosky_msgs__LANE_FILTER_PARAMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace rosky_msgs
{
  class Lane_Filter_ParamConfigStatics;

  class Lane_Filter_ParamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(Lane_Filter_ParamConfig &config, const Lane_Filter_ParamConfig &max, const Lane_Filter_ParamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const Lane_Filter_ParamConfig &config1, const Lane_Filter_ParamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, Lane_Filter_ParamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const Lane_Filter_ParamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Lane_Filter_ParamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const Lane_Filter_ParamConfig &config) const = 0;
      virtual void getValue(const Lane_Filter_ParamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T Lane_Filter_ParamConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T Lane_Filter_ParamConfig::* field;

      virtual void clamp(Lane_Filter_ParamConfig &config, const Lane_Filter_ParamConfig &max, const Lane_Filter_ParamConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const Lane_Filter_ParamConfig &config1, const Lane_Filter_ParamConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, Lane_Filter_ParamConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const Lane_Filter_ParamConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Lane_Filter_ParamConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const Lane_Filter_ParamConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const Lane_Filter_ParamConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, Lane_Filter_ParamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, Lane_Filter_ParamConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<Lane_Filter_ParamConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(Lane_Filter_ParamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("mean_d_0"==(*_i)->name){mean_d_0 = boost::any_cast<double>(val);}
        if("mean_phi_0"==(*_i)->name){mean_phi_0 = boost::any_cast<double>(val);}
        if("sigma_d_0"==(*_i)->name){sigma_d_0 = boost::any_cast<double>(val);}
        if("sigma_phi_0"==(*_i)->name){sigma_phi_0 = boost::any_cast<double>(val);}
        if("delta_d"==(*_i)->name){delta_d = boost::any_cast<double>(val);}
        if("delta_phi"==(*_i)->name){delta_phi = boost::any_cast<double>(val);}
        if("d_max"==(*_i)->name){d_max = boost::any_cast<double>(val);}
        if("d_min"==(*_i)->name){d_min = boost::any_cast<double>(val);}
        if("phi_min"==(*_i)->name){phi_min = boost::any_cast<double>(val);}
        if("phi_max"==(*_i)->name){phi_max = boost::any_cast<double>(val);}
        if("cov_v"==(*_i)->name){cov_v = boost::any_cast<double>(val);}
        if("linewidth_while"==(*_i)->name){linewidth_while = boost::any_cast<double>(val);}
        if("linewidth_yellow"==(*_i)->name){linewidth_yellow = boost::any_cast<double>(val);}
        if("lane_width"==(*_i)->name){lane_width = boost::any_cast<double>(val);}
        if("min_max"==(*_i)->name){min_max = boost::any_cast<double>(val);}
        if("use_min_segs"==(*_i)->name){use_min_segs = boost::any_cast<bool>(val);}
        if("min_segs"==(*_i)->name){min_segs = boost::any_cast<int>(val);}
        if("use_maximum_segment_dist"==(*_i)->name){use_maximum_segment_dist = boost::any_cast<bool>(val);}
        if("max_segment_dist"==(*_i)->name){max_segment_dist = boost::any_cast<double>(val);}
        if("use_distance_weighting"==(*_i)->name){use_distance_weighting = boost::any_cast<bool>(val);}
        if("zero_val"==(*_i)->name){zero_val = boost::any_cast<int>(val);}
        if("l_peak"==(*_i)->name){l_peak = boost::any_cast<int>(val);}
        if("peak_val"==(*_i)->name){peak_val = boost::any_cast<int>(val);}
        if("l_max"==(*_i)->name){l_max = boost::any_cast<int>(val);}
        if("use_propagation"==(*_i)->name){use_propagation = boost::any_cast<bool>(val);}
        if("sigma_d_mask"==(*_i)->name){sigma_d_mask = boost::any_cast<double>(val);}
        if("sigma_phi_mask"==(*_i)->name){sigma_phi_mask = boost::any_cast<double>(val);}
      }
    }

    double mean_d_0;
double mean_phi_0;
double sigma_d_0;
double sigma_phi_0;
double delta_d;
double delta_phi;
double d_max;
double d_min;
double phi_min;
double phi_max;
double cov_v;
double linewidth_while;
double linewidth_yellow;
double lane_width;
double min_max;
bool use_min_segs;
int min_segs;
bool use_maximum_segment_dist;
double max_segment_dist;
bool use_distance_weighting;
int zero_val;
int l_peak;
int peak_val;
int l_max;
bool use_propagation;
double sigma_d_mask;
double sigma_phi_mask;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mean_d_0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mean_phi_0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_d_0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_phi_0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double delta_d;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double delta_phi;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double d_max;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double d_min;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double phi_min;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double phi_max;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cov_v;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double linewidth_while;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double linewidth_yellow;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lane_width;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_max;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_min_segs;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_segs;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_maximum_segment_dist;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_segment_dist;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_distance_weighting;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int zero_val;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int l_peak;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int peak_val;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int l_max;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_propagation;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_d_mask;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sigma_phi_mask;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("Lane_Filter_ParamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const Lane_Filter_ParamConfig &__max__ = __getMax__();
      const Lane_Filter_ParamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const Lane_Filter_ParamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const Lane_Filter_ParamConfig &__getDefault__();
    static const Lane_Filter_ParamConfig &__getMax__();
    static const Lane_Filter_ParamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const Lane_Filter_ParamConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void Lane_Filter_ParamConfig::ParamDescription<std::string>::clamp(Lane_Filter_ParamConfig &config, const Lane_Filter_ParamConfig &max, const Lane_Filter_ParamConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class Lane_Filter_ParamConfigStatics
  {
    friend class Lane_Filter_ParamConfig;

    Lane_Filter_ParamConfigStatics()
    {
Lane_Filter_ParamConfig::GroupDescription<Lane_Filter_ParamConfig::DEFAULT, Lane_Filter_ParamConfig> Default("Default", "", 0, 0, true, &Lane_Filter_ParamConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mean_d_0 = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mean_d_0 = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mean_d_0 = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("mean_d_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::mean_d_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("mean_d_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::mean_d_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mean_phi_0 = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mean_phi_0 = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mean_phi_0 = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("mean_phi_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::mean_phi_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("mean_phi_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::mean_phi_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_d_0 = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_d_0 = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_d_0 = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_d_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_d_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_d_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_d_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_phi_0 = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_phi_0 = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_phi_0 = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_phi_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_phi_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_phi_0", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_phi_0)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.delta_d = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.delta_d = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.delta_d = 0.02;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("delta_d", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::delta_d)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("delta_d", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::delta_d)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.delta_phi = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.delta_phi = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.delta_phi = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("delta_phi", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::delta_phi)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("delta_phi", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::delta_phi)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.d_max = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.d_max = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.d_max = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("d_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::d_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("d_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::d_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.d_min = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.d_min = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.d_min = -0.15;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("d_min", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::d_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("d_min", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::d_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.phi_min = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.phi_min = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.phi_min = -1.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("phi_min", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::phi_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("phi_min", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::phi_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.phi_max = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.phi_max = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.phi_max = 1.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("phi_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::phi_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("phi_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::phi_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cov_v = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cov_v = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cov_v = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("cov_v", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::cov_v)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("cov_v", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::cov_v)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.linewidth_while = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.linewidth_while = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.linewidth_while = 0.017;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("linewidth_while", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::linewidth_while)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("linewidth_while", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::linewidth_while)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.linewidth_yellow = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.linewidth_yellow = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.linewidth_yellow = 0.017;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("linewidth_yellow", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::linewidth_yellow)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("linewidth_yellow", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::linewidth_yellow)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lane_width = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lane_width = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lane_width = 0.22;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("lane_width", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::lane_width)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("lane_width", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::lane_width)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_max = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_max = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_max = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("min_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::min_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("min_max", "double", 0, "Basic parameter for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::min_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_min_segs = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_min_segs = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_min_segs = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_min_segs", "bool", 0, "Minimum number of segments for generating measurement for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_min_segs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_min_segs", "bool", 0, "Minimum number of segments for generating measurement for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_min_segs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_segs = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_segs = 20;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_segs = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("min_segs", "int", 0, "Minimum number of segments for generating measurement for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::min_segs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("min_segs", "int", 0, "Minimum number of segments for generating measurement for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::min_segs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_maximum_segment_dist = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_maximum_segment_dist = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_maximum_segment_dist = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_maximum_segment_dist", "bool", 0, "maximum segment distance for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_maximum_segment_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_maximum_segment_dist", "bool", 0, "maximum segment distance for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_maximum_segment_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_segment_dist = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_segment_dist = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_segment_dist = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("max_segment_dist", "double", 0, "maximum segment distance for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::max_segment_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("max_segment_dist", "double", 0, "maximum segment distance for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::max_segment_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_distance_weighting = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_distance_weighting = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_distance_weighting = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_distance_weighting", "bool", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_distance_weighting)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_distance_weighting", "bool", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_distance_weighting)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zero_val = -10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zero_val = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zero_val = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("zero_val", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::zero_val)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("zero_val", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::zero_val)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_peak = -10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_peak = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_peak = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("l_peak", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::l_peak)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("l_peak", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::l_peak)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.peak_val = -10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.peak_val = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.peak_val = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("peak_val", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::peak_val)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("peak_val", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::peak_val)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.l_max = -10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.l_max = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.l_max = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("l_max", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::l_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<int>("l_max", "int", 0, "distance weighting for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::l_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_propagation = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_propagation = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_propagation = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_propagation", "bool", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_propagation)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<bool>("use_propagation", "bool", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::use_propagation)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_d_mask = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_d_mask = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_d_mask = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_d_mask", "double", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_d_mask)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_d_mask", "double", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_d_mask)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sigma_phi_mask = -10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sigma_phi_mask = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sigma_phi_mask = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_phi_mask", "double", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_phi_mask)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr(new Lane_Filter_ParamConfig::ParamDescription<double>("sigma_phi_mask", "double", 0, "use_propagation for Lane_Filiter_node", "", &Lane_Filter_ParamConfig::sigma_phi_mask)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(Lane_Filter_ParamConfig::AbstractGroupDescriptionConstPtr(new Lane_Filter_ParamConfig::GroupDescription<Lane_Filter_ParamConfig::DEFAULT, Lane_Filter_ParamConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<Lane_Filter_ParamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<Lane_Filter_ParamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    Lane_Filter_ParamConfig __max__;
    Lane_Filter_ParamConfig __min__;
    Lane_Filter_ParamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const Lane_Filter_ParamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static Lane_Filter_ParamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &Lane_Filter_ParamConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const Lane_Filter_ParamConfig &Lane_Filter_ParamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const Lane_Filter_ParamConfig &Lane_Filter_ParamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const Lane_Filter_ParamConfig &Lane_Filter_ParamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<Lane_Filter_ParamConfig::AbstractParamDescriptionConstPtr> &Lane_Filter_ParamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<Lane_Filter_ParamConfig::AbstractGroupDescriptionConstPtr> &Lane_Filter_ParamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const Lane_Filter_ParamConfigStatics *Lane_Filter_ParamConfig::__get_statics__()
  {
    const static Lane_Filter_ParamConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = Lane_Filter_ParamConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LANE_FILTER_PARAMRECONFIGURATOR_H__
