// Generated by gencpp from file rosky_msgs/SetFSMState.msg
// DO NOT EDIT!


#ifndef ROSKY_MSGS_MESSAGE_SETFSMSTATE_H
#define ROSKY_MSGS_MESSAGE_SETFSMSTATE_H

#include <ros/service_traits.h>


#include <rosky_msgs/SetFSMStateRequest.h>
#include <rosky_msgs/SetFSMStateResponse.h>


namespace rosky_msgs
{

struct SetFSMState
{

typedef SetFSMStateRequest Request;
typedef SetFSMStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFSMState
} // namespace rosky_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosky_msgs::SetFSMState > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::rosky_msgs::SetFSMState&) { return value(); }
};

template<>
struct DataType< ::rosky_msgs::SetFSMState > {
  static const char* value()
  {
    return "rosky_msgs/SetFSMState";
  }

  static const char* value(const ::rosky_msgs::SetFSMState&) { return value(); }
};


// service_traits::MD5Sum< ::rosky_msgs::SetFSMStateRequest> should match
// service_traits::MD5Sum< ::rosky_msgs::SetFSMState >
template<>
struct MD5Sum< ::rosky_msgs::SetFSMStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosky_msgs::SetFSMState >::value();
  }
  static const char* value(const ::rosky_msgs::SetFSMStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosky_msgs::SetFSMStateRequest> should match
// service_traits::DataType< ::rosky_msgs::SetFSMState >
template<>
struct DataType< ::rosky_msgs::SetFSMStateRequest>
{
  static const char* value()
  {
    return DataType< ::rosky_msgs::SetFSMState >::value();
  }
  static const char* value(const ::rosky_msgs::SetFSMStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosky_msgs::SetFSMStateResponse> should match
// service_traits::MD5Sum< ::rosky_msgs::SetFSMState >
template<>
struct MD5Sum< ::rosky_msgs::SetFSMStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosky_msgs::SetFSMState >::value();
  }
  static const char* value(const ::rosky_msgs::SetFSMStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosky_msgs::SetFSMStateResponse> should match
// service_traits::DataType< ::rosky_msgs::SetFSMState >
template<>
struct DataType< ::rosky_msgs::SetFSMStateResponse>
{
  static const char* value()
  {
    return DataType< ::rosky_msgs::SetFSMState >::value();
  }
  static const char* value(const ::rosky_msgs::SetFSMStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSKY_MSGS_MESSAGE_SETFSMSTATE_H
